---
title: "Posters vs. Talks"
date: 2011-07-01
categories: 
  - "english"
---

This is my view on organization of scientific conferences, especially the mid-size and large ones. In my opinion **poster sessions** are a much more efficient way of scientific communication than a bunch of 20 minutes talks. I advocate for upgrading the scientific prestige posters deliver to the author to be larger than the prestige of short talks. <!--more--> Posters can give a solid overview of a paper and can easily be extracted from them. In a poster session you as the visitor can select what you are interested in. You can save time in two ways: First, you do not need to wait for the thing you are interested in. Second, by asking the author you can quickly come to your problems of understanding. This avoids what usually happens with talks: Half of the audience lacks background knowledge and gets lost, while the other half gets bored by the attempt of the speaker to attract and keep the others. Unfortunately, posters seem to be regarded as the least prestigious scientific output. Facing my argument the prestige of a talk lies in the "right to use (and likely waste) the time of many others". Don't get me wrong: I also think that a conference needs some central gatherings like entertaining key notes or a "Poster Spotlight" where everyone has the right to advertise her poster in one minute and one slide.
