project:
  type: website

website:
  title: "Jan Lorenz"
  description: "Jan Lorenz is Assistant Professor of Social Data Science at Constructor University Bremen doing data-driven agent-based modeling in computational social science."
#  favicon: "/files/favicon-512.png"
  site-url: "https://www.janlo.de"
  repo-url: "https://github.com/janlorenz/janlo"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd
      - teaching.qmd
      - scientific-events.qmd
      - constructor-labs.qmd
      - blog.qmd


format:
  html:
    theme: simplex #flatly  # simplex
    css: styles.css
    toc: true

bibliography: references/references.bib
csl: references/apa-cv.csl
