---
title: "Analysen und Reformvorschläge zum Wahlrecht zur Bremischen Bürgerschaft"
date: 2016-04-06
categories: 
  - "data-analysis"
  - "deutsch"
---

Dieser Text argumentiert für diesen [**Reformvorschlag**](https://docs.google.com/document/d/1EeDf1BGWRaF2oLRkzOOPl30YgDullOL18Eo_Mphz9jg/edit?usp=sharing).

Der Weser-Kurier [\[1\]](#1) schrieb im Februar 2016, **SPD und CDU wollten möglichst zügig ein neues Wahlrecht in der Bürgerschaft verabschieden**. Neben Heilungsregeln für zur Zeit ungültige Wahlzettel geht es vor allem um zwei Dinge:

**1\. Es sollen die Hälfte der Mandate einer Partei per Parteiliste und die andere Hälfte per Wählerrangliste nach Personenstimmen vergeben werden.** Das Verhältnis soll nicht mehr, wie jetzt, durch das Verhältnis von Personen- und Listenstimmen bestimmt werden.

**2\. Es soll zuerst die Wählerrangliste und dann die Parteiliste abgearbeitet werden.** Derzeit ist es anders herum. Als Grund wird genannt, dass die Personenbank eigentlich hauptsächlich durch die Spitzenkandidat\_innen "überhand" genommen hätte und dass dadurch auch einige Kandidiernde in die Bürgerschaft kamen, für die nur wenige hundert Stimmen abgegeben worden wären. \[Update 26.5.2016: Inzwischen haben sich auch DIE LINKE [\[5\]](#5) und GRÜNE [\[6\]](#6) auf Landesparteitagen für die Umkehrung der Reihenfolge aber gegen die starre hälftige Aufteilung ausgesprochen.\]

**In diesem Beitrag stelle ich eine neue [detailiertere Analyse der Wahldaten](https://docs.google.com/spreadsheets/d/1O0aVHYYX6W5Lzm8BIncARW77Fa-Txdzv5zbdvaNrHY8/pubhtml) von 2015 vor, sowie zum Vergleich die gleiche Analyse zur Wahl 2011.** <!--more-->Damit möchte ich zu einer informierteren Bewertung der Lage auch im Detail (z.B. auf Kandidierenden-Ebene) beitragen. Die Analyse, sowie auch dieser Artikel kann kommentiert werden. Kurz zusammengefasst: Die durch die Personenstimmen erzeugte Wählerrangliste der Kandidierenden und von den Parteimitgliedern festgelegt Parteilisten sind bei allen in der Bürgerschaft vertretenen Parteien sehr ähnlich und bei weitem nicht gegensätzlich. Gleichzeitig gibt es einen Trend zu mehr Personenstimmen, deren Anteil aber trotzdem noch unter 50% liegt. Gleichzeitig wurden aber der Stimmenanteil der Spitzenkandidat\_innen weniger (von 19.1% auf 18.5%), insbesondere bei der Bürgermeister-Partei SPD (von 32.8% auf 28.6%) und das trotz eines Wahlkampfes der stark auf die Spitzenkandidat\_innen fokussierte. **Die Personenwahlmöglichkeiten des neuen Wahlrechts werden also durch die Wählenden sowohl mehr als auch kompetenter genutzt.** Da Parteiliste und Wählerrangliste ähnlich sind, geht es mit der Umkehrung der Reihenfolge praktisch um die Frage, welcher Liste der Vorrang bei den "unsicheren" Mandaten gegeben werden soll. Modellrechnungen zeigen hier, dass nach dem neuen Vorschlag nur noch 10.8% der Abgeordneten abweichend von den Parteilisten in die Bürgerschaft einzögen. Derzeit sind es 26.5%. Würde nur die Rangliste der Wählenden benutzt, wären es kaum mehr, nämlich 31.3%. **Parteien und Wähler sind sich also zur Zeit schon eher einig als uneinig, weshalb es hier eigentlich konsequent und politisch machbar erscheint, ganz auf den Wählerwillen auch bei den Personen zu setzen.**

Die [Datenanalyse](https://docs.google.com/spreadsheets/d/1O0aVHYYX6W5Lzm8BIncARW77Fa-Txdzv5zbdvaNrHY8/pubhtml) zeigt allerdings auch die Relevanz einer bisher weniger beachteten Eigenschaft des Bremer Wahlsystems: **Es gibt Kandidierenden gut Chancen, die auf viele Personenstimmen von vergleichsweise wenigen Wählenden setzen. Dadurch haben es Kandidierende schwerer, die mehr Wählende ansprechen, aber von denen eher nur eine Stimme erhalten.** Beispielsweise wird eine Kandidatin, die von nur 300 Wählenden alle fünf Stimmen bekommt, genauso eingeordnet wie eine Kandidatin die von 1500 Wählenden je eine Stimme bekommt. Tatsächlich gibt es in der Bürgerschaft Kandidierende, die eher dem einen oder eher dem anderen Typ entsprechen. Es zeigt sich allerdings ein Trend in Richtung des ersten Typs. Auch die Wählenden stehen vor der Frage, ob sie nicht aus rein strategischen Gründen alle Stimmen auf einen Kandidierenden kummulieren sollen. Der Anreiz strategisch zu wählen ist besonders stark gerade für die Wählenden, die sich viel über Kandidierende informieren und schon eine Liste von fünf Favoriten abseits der bekannten Gesichter also auf unsicheren Plätzen haben. Dies scheint mir eigentlich nicht "im Sinne der Erfinder" zu sein. Langfristig verstärkt die Möglichkeit alle fünf Stimmen zu kummulieren, glaube ich, Polarisierungstendenzen sowohl in den Fraktionen der Bürgerschaft, als auch in der Bevölkerung. **Ein neuer [Vorschlag](https://docs.google.com/document/d/1EeDf1BGWRaF2oLRkzOOPl30YgDullOL18Eo_Mphz9jg/edit#heading=h.aehyqs7ax4xa) für eine Wahlrechtsreform ist daher: Einerseits ganz auf die Wählerrangliste zu setzen, aber dafür andererseits auf die Anzahl der Wähler und nicht die Anzahl der Stimmen zu setzen.** In der Umsetzung würde dies bedeuten, dass man als Wählender jedem Kandidierenden maximal eine Stimme geben kann, aber weiterhin fünf Stimmen (oder perspektivisch sogar mehr) abgeben kann.

Das aktuelle Wahlrecht, den Vorschlag von SPD und CDU, sowie den neuen Vorschlag vergleicht folgende Tabelle:

|  | **Aktuelles Wahlrecht** | **Vorschlag A  (SPD/CDU)** | **Vorschlag B (Neu)** |
| :-- | :-: | :-: | :-: |
| Anzahl Mandate per Wählerrangliste | Nach Anteil der Personen-stimmen an Gesamtstimmen | 50.00% | Alle |
| Unsichere Mandate vergeben nach | Wählerrangliste | Parteiliste | Wählerrangliste |
| Wieviele Stimmen maximal pro Kandidat\_in | 5 von 5 | 5 von 5 | 1 von 5 |
| Personenstimmenparadox | Ja | Nein | Nein |
| Mandatsrelevanz der Personenstimmen 2015 | 26.50% | 10.80% | 26.50% |

Das Personenstimmenparadox wird hier nur erwähnt, weil es einen gewissen verfassungsmäßig gebotenen Reformbedarf erzeugt. Es wurde von Valentin Schröder und Lothar Probst [\[2,3\]](#2) zu recht problematisiert. In ihren Lösungsvorschlägen [\[3\]](#3) fehlt allerdings die Lösung, ganz auf die Reihenfolge der Wählenden zu setzen.

Die Datenanalyse bietet **Modellrechnungen** inklusive den hypothetisch dann gewählten Personen für alle drei Wahlsystem (die Links öffnen die Ergebnisse in Google Spreadsheet): [Aktuelles Wahlrecht 2015](https://docs.google.com/spreadsheets/d/1O0aVHYYX6W5Lzm8BIncARW77Fa-Txdzv5zbdvaNrHY8/edit#gid=692618892) [Reformvorschlag A: 50/50, Personenrangliste zuerst 2015](https://docs.google.com/spreadsheets/d/1O0aVHYYX6W5Lzm8BIncARW77Fa-Txdzv5zbdvaNrHY8/edit#gid=1916215620) [Reformvorschlag B: Wähleranzahlrangliste 2015](https://docs.google.com/spreadsheets/d/1O0aVHYYX6W5Lzm8BIncARW77Fa-Txdzv5zbdvaNrHY8/edit#gid=1532329419) Hinweis: Die Ergebnisse beziehen sich auf die Zählung noch vor der [Entscheidung des Bremer Wahlprüfungsgerichts](http://www.verwaltungsgericht.bremen.de/sixcms/media.php/13/15_1330_K_14.pdf) das Ergebnis zu korregieren. Bei den Listen der potentiellen Mitglieder der Bremischen Bürgerschaft sind Mandatsniederlegungen und Nachrückungen auch nicht berücksichtigt.

Der **Unterschied der drei Systeme** lässt sich an dem interessanten **Beispiel der Grünen-Liste in Bremerhaven** erläutern. Die Grünen errangen dort zwei Mandate, nach aktuellem Wahlrecht wird davon einer nach der Parteiliste und einer nach der Wählerrangliste vergeben. Das gleiche wäre im Falle von Vorschlag A der Fall. Bei Vorschlag B würden beide Mandate nach der Wählerrangliste vergeben werden. Sülmez Dogan ist auf Platz 1 der Liste und führt mit 3058 Personenstimmen von 1318 Wählenden sowohl die Wählerrangliste nach Personenstimmen, als auch die nach de Anzahl der Wählenden an. D.h. sie erhält nach allen drei Systemen das erste Mandat. Nach aktuellem Wahlrecht bekommt sie das Listenmandat, nach Vorschlag A das Personenmandat. Spannend wird es bei Platz zwei. Nach aktuellem Wahlrecht, bekam Turhal Özdal das Personenstimmenmandat da er mit 837 die zweitmeisten Personenstimmen hat. Da er nur auf Listenplatz neun steht wäre er nach Vorschlag A abgeschlagen für den Listensitz, den würde Frank Willmann bekommen der auf Platz zwei steht aber nur 715 Stimmen hat. Auch nach Vorschlag B wäre Özdal nicht gewählt, da sechs Listenmitglieder ihre (weniger) Stimmen von mehr Wählenden haben. Gewählt wäre Ulf Eversberg, der zwar nur 737 Stimmen hat, diese kommen aber von 424 Wählenden. Turhal Özdal ist inzwischen bei den Grünen ausgetreten und der Fraktion der CDU beigetreten. Dies ist sein legitimes Recht, er hat es darüber hinaus auch Forderungen der Grünen, sein Mandat niederzulegen, mit der Begründung zurückgewiesen, dass er über Personenstimmen gewählt sei [\[4\]](#4). \[Update 26.5.2016: Die Spitzenkandidatin und Finanzsenatorin der GRÜNEN Karoline Linnert wird im Weser-Kurier [\[6\]](#6) zitiert "das geltende Wahlrecht befördere die 'Partikularinteressen von Ethnien, Cliquen und Peer-Groups'." Das ist eine drastischere Interpretation von Polarisierungstendenzen. Der Vorschlag der GRÜNEN die Reihenfolge der Zuteilung umzukehren, befördert Polarisierungstendenzen aber weiter, da er nichts an den strategischen Anreizen für Wählende und Kandidierende ändert alle 5 Stimme geschlossen abzugeben bzw. einzuwerben.\]

**Fazit:** Das Bremer Wahlrecht neigt möglicherweise dazu, Polarisierungstendenzen in Fraktionen und Bevölkerung zu verstärken. Innerhalb der Fraktionen ist dies auch schon beobachtbar, weshalb es Bestrebungen zumindest bei SPD, CDU, Grünen und Linken gibt, den Einfluss der Wählenden wieder faktisch deutlich zurück zu drehen, obwohl die Wählenden ihn zunehmend und kompetenter nutzen. Ein besserer Reformansatz wäre, an der Anzahl der Kummuliermöglichkeiten für Personenstimmen anzusetzen. Auch aus normativen Gründen ist es nicht unbedingt konsequent alle Stimmen für einen Kandidierenden im Wahlsystem anzubieten. Es soll schließlich ein Parlament gewählt werden und nicht eine Person. Die Personenstimme ist hauptsächlich eine Stimme für die Liste der sich der Kandidierende angeschlossen hat und erst im zweiten Schritt Bekenntnis der besonderen Zustimmung zu dieser Person. Das aktuelle Wahlrecht war gut, da es den Wählenden die bekannte reine Listenwahl gelassen hat. Auch die fünf Kummuliermöglichkeiten haben sicherlich schnell "Schwung" in die Parteilisten gebracht in dem es gezeigt hat, dass dort für Wählende und Kandidierende etwas möglich ist. Jetzt sollte das Wahlrecht weiterentwickelt werden in dem die Polarisierungsverstärkung abgebaut wird ohne den Einfluss der Wählenden zurückzudrehen. Zum Beispiel mit diesem einfachen [Vorschlag](https://docs.google.com/document/d/1EeDf1BGWRaF2oLRkzOOPl30YgDullOL18Eo_Mphz9jg/edit#heading=h.aehyqs7ax4xa).

 

\[1\] [SPD und CDU wollen Wahlrechtsreform vorantreiben](http://www.weser-kurier.de/bremen/bremen-politik-wirtschaft_artikel,-SPD-und-CDU-wollen-Wahlrechtsreform-vorantreiben-_arid,1316733.html), Jürgen Theiner, _Weser-Kurier_, 19.2.2016 \[2\] [Fremdverwertung und Personenstimmenparadox: Negatives Stimmgewicht im Bremer und Hamburger Bürgerschaftswahlrecht](http://dx.doi.org/10.5771/0340-1758-2015-3-561),Valentin Schröder, _Zeitschrift für Parlamentsfragen_, **2015**_, 46_, 561-577 \[3\] [Das Bremer Wahlsystem: Intransparent, paradox und möglicherweise verfassungswidrig](http://www.lotharprobst.de/fileadmin/user_upload/redakteur/Aktuelles/2015/Effekte_Wahlsystem_2015.pdf), Lothar Probst, Valentin Schröder, Institut für Politikwissenschaft, Universität Bremen \[4\] [Ex-Grüner will zur CDU](http://www.radiobremen.de/politik/themen/oezdal-wechselt100.html), Radio Bremen 20. Februar 2016 \[5\] [Landesparteitag kritisiert Festhalten des Senats an Schuldenbremse und diskutiert mögliche Wahlrechtsreform](http://www.dielinke-bremen.de/nc/politik/aktuell/detail/browse/1/zurueck/bremennews/artikel/landesparteitag-kritisiert-festhalten-des-senats-an-schuldenbremse-und-diskutiert-moegliche-wahlrech/), DIE LINKE Landesverband Bremen, 25.4.2016 \[6\] [Grüne für Wahlrechtsreform](http://www.weser-kurier.de/bremen_artikel,-Gruene-fuer-Wahlrechtsreform-_arid,1369422.html), Jürgen Theiner, _Weser-Kurier_, 4.5.2016
