---
title: "Wahlrecht im Weser-Kurier"
date: 2018-02-21
categories: 
  - "deutsch"
---

Zum Artikel ["Bremer Wahlrecht: Kritik aus der Wissenschaft"](https://www.weser-kurier.de/bremen/bremen-stadt_artikel,-bremer-wahlrecht-kritik-aus-der-wissenschaft-_arid,1702418.html) im Weser Kurier vom 21.2.2018 stelle ich hier folgende Links bereit:

- Mein Blog-Beitrag ["Analysen und Reformvorschläge zum Wahlrecht zur Bremischen Bürgerschaft"](http://janlo.de/wp/2016/04/06/analysen-reformvorschlage-wahlrecht-bremische-burgerschaft/) vom 6.4.2017 mit einer genaueren Erläuterung.
- Begleitend gibt es die [Detailierten Analyse der Wahlen zur Bremischen Bürgerschaft 2011 und 2015](https://docs.google.com/spreadsheets/d/1O0aVHYYX6W5Lzm8BIncARW77Fa-Txdzv5zbdvaNrHY8/pubhtml). Insbesondere gibt es dort
    - unter der Überschrift "Personenstimmenrangliste 2015" die Zahlen zur Anzahl der Stimmen im Verhältnis zur Anzahl der Wähler für alle Kandidaten.
    - unter der Überschrift "Vergleich Mandate Reformvorschläge 2015" die Parteilisten, die Personenstimmenranglisten und die Ranglisten nach der Anzahl der Wähler im Vergleich, sowie hypothetische Mandatsvergaben für verschiedene Versionen der Mandatsvergabe. Die von mir vorgeschlagene Änderung ist Vorschlag D. In der Bürgerschaft steht der Vorschlag A zur Abstimmung.
- Hier sind die Folien meines Habilitationsvortrages ["Strategic voter and candidate behavior in open list voting systems with many votes. The case of Bremen theoretically and empirically"](http://janlo.de/talks/habil_lorenz_talk_2017.pdf) an der Jacobs Uni.
- Ein Fachartikel auf deutsch zu dem Thema liegt derzeit bei der Zeitschrift für Parlamentsfragen zur Begutachtung. Er wird hier verlinkt, sobald er erscheint.
- Aus der Bremischen Bürgerschaft hier der Link zum [Bericht des Wahlrechtsausschuss](http://www.bremische-buergerschaft.de/dokumente/wp19/land/drucksache/D19L1487.pdf) der die Grundlage für die Entscheidung in dieser Woche darstellt. Interessantes Detail: Das jetzige Wahlrecht wird als **verfassungsrechtlich höchst bedenklich** bezeichnet, da z.B. bei Thomas von Bruch (CDU) 2015 das Personenstimmenparadox (negatives Stimmengewicht bei der Personenauswahl) aufgetreten ist. Die vorgeschlagene Änderung ist allerding **theoretisch (und  empirisch nicht vernachlässigbar) genauso verfassungsrechtlich höchst bedenklich**. Das negatives Stimmengewicht träte mit dem vorgeschlagenen Wahlrecht 2015 genauso auf, nur bei Anne Schierenbeck (GRÜNE). \[Update 2018-02-22: Der Kommentar unten zeigt richtig auf, dass ich mich bei der gestrichenen Aussage zu Anne Schierenbeck geirrt habe. Erläuterung und andere interessante Fälle unten im Kommentar. Meine nachfolgende Schlussfolgerung bleibt davon allerdings unbenommen.\] **Entweder wurde hier sehr schlurig gearbeitet, oder die Bürgerschaft soll getäuscht werden, in dem so getan wird, als würde eine verfassungsrechtliche Bedenklichkeit abgeschafft. Das ist nicht der Fall.** 

**Erklärung Personenstimmenparadox**: Personenstimmen können den Mandatserwerb eines Kandidaten verhindetn, wenn er oder sie der nächste Kandidate auf der Liste ist, der ein Mandat bekommen würde. Unter gewissen Bedingungen würden seine Personenstimmen als Listenstimmen abgegeben die Listenbank um eine Person vergrößern (und die Personenstimmenbank verkleinern) und so zu einem Mandatserwerb führen. Das Phänomen ist eine theoretische Folger der nach der Anzahl der Listenstimmen festgelegten Größe der Listenbank. Empirisch tritt es auf, wenn Parteilisten und Wählerlisten sich eher ähneln als gegenläufig sind, was entgegen mancher Äußerungen, immer noch deutlich der Fall ist. Der Name Personenstimmenparadox stammt von Valentin Schröder (Uni Bremen): [Fremdverwertung und Personenstimmenparadox: Negatives Stimmgewicht im Bremer und Hamburger Bürgerschaftswahlrecht](http://dx.doi.org/10.5771/0340-1758-2015-3-561),Valentin Schröder, _Zeitschrift für Parlamentsfragen_, **2015**_, 46_, 561-577
